language: python
python:
    - '3.8'
    - '3.7'
    - '3.6'
    - '3.5'
    - '3.4'
    - '2.7'

install:
    - pip install .

script:
    - pytest -v

notifications:
    email:
      on_success: never